import 'package:flutter/material.dart';
import '../models/user.dart';
import '../models/project.dart';
import '../models/resource_assessment.dart';
import '../models/financial_model.dart';
import '../models/diagnostic_report.dart';

class MockData {
  static final User mockUser = User(
    id: 'user_001',
    email: 'wei.zhang@huaneng.com',
    phone: '+86 13800138000',
    fullName: '张伟',
    company: '华能新能源有限公司',
    jobTitle: '项目经理',
    userRole: 'project_manager',
    subscriptionTier: 'professional',
    apiCallsToday: 45,
    apiCallsLimit: 500,
  );

  static final List<Project> mockProjects = [
    Project(
      id: 'proj_001',
      userId: 'user_001',
      name: '山东德州100MW光伏电站',
      projectType: 'solar_pv',
      status: 'operating',
      lat: 37.5273,
      lng: 116.3004,
      address: '山东省德州市陵城区',
      province: '山东',
      capacityMw: 100.0,
      tags: ['大型光伏', '地面电站', 'A级资源'],
      createdAt: DateTime.now().subtract(Duration(days: 365)),
    ),
    Project(
      id: 'proj_002',
      userId: 'user_001',
      name: '内蒙古乌兰察布50MW风电场',
      projectType: 'wind',
      status: 'operating',
      lat: 41.0028,
      lng: 113.1137,
      address: '内蒙古自治区乌兰察布市',
      province: '内蒙古',
      capacityMw: 50.0,
      tags: ['风电', 'III类风区', '运营中'],
      createdAt: DateTime.now().subtract(Duration(days: 720)),
    ),
    Project(
      id: 'proj_003',
      userId: 'user_001',
      name: '广东惠州25MWh储能系统',
      projectType: 'storage',
      status: 'construction',
      lat: 23.1291,
      lng: 114.3055,
      address: '广东省惠州市惠城区',
      province: '广东',
      capacityMw: 25.0,
      tags: ['锂电池', '峰值调频', '建设中'],
      createdAt: DateTime.now().subtract(Duration(days: 90)),
    ),
    Project(
      id: 'proj_004',
      userId: 'user_001',
      name: '宁夏银川200MW光伏+风电混合',
      projectType: 'hybrid',
      status: 'planning',
      lat: 38.4680,
      lng: 106.2586,
      address: '宁夏回族自治区银川市',
      province: '宁夏',
      capacityMw: 200.0,
      tags: ['混合能源', '沙漠光伏', '规划阶段'],
      createdAt: DateTime.now().subtract(Duration(days: 30)),
    ),
  ];

  static final List<Map<String, dynamic>> mockAlerts = [
    {
      'id': 'alert_001',
      'severity': 'critical',
      'project': '山东德州100MW光伏电站',
      'message': '逆变器故障：PCS-12号机组离线',
      'timestamp': DateTime.now().subtract(Duration(minutes: 15)),
      'status': '待处理',
    },
    {
      'id': 'alert_002',
      'severity': 'warning',
      'project': '内蒙古乌兰察布50MW风电场',
      'message': '预警：风机叶片需要检查维护',
      'timestamp': DateTime.now().subtract(Duration(hours: 2)),
      'status': '已处理',
    },
    {
      'id': 'alert_003',
      'severity': 'info',
      'project': '广东惠州25MWh储能系统',
      'message': '信息：电池组温度正常范围',
      'timestamp': DateTime.now().subtract(Duration(hours: 6)),
      'status': '已读',
    },
  ];

  static final ResourceAssessment mockSolarAssessment = ResourceAssessment(
    id: 'assess_solar_001',
    assessmentType: 'solar',
    lat: 37.5273,
    lng: 116.3004,
    ghiAnnual: 1456.8,
    dniAnnual: 1876.5,
    windSpeedAnnual: 3.2,
    windPowerDensity: 0,
    weibullK: 0,
    turbulenceIntensity: 0,
    siteScore: 72.5,
    siteGrade: 'B',
    recommendation: '该地区属于二类资源区，光照条件良好，建议采用固定式安装方案，预期年发电小时数约1350-1400小时。',
    ghiMonthly: [87.4, 104.3, 142.8, 156.9, 168.2, 155.6, 145.3, 138.7, 118.4, 102.6, 78.9, 72.3],
    temperatureMonthly: [-2.5, 0.8, 8.6, 18.3, 26.7, 31.2, 32.1, 30.8, 25.4, 16.8, 6.3, -1.4],
    windSpeedMonthly: [3.1, 3.2, 3.4, 3.2, 3.0, 2.9, 2.8, 2.9, 3.1, 3.3, 3.5, 3.4],
  );

  static final ResourceAssessment mockWindAssessment = ResourceAssessment(
    id: 'assess_wind_001',
    assessmentType: 'wind',
    lat: 41.0028,
    lng: 113.1137,
    ghiAnnual: 0,
    dniAnnual: 0,
    windSpeedAnnual: 7.4,
    windPowerDensity: 185.6,
    weibullK: 2.15,
    turbulenceIntensity: 0.16,
    siteScore: 78.3,
    siteGrade: 'B',
    recommendation: '该地区属于Ⅱ类风区，年平均风速7.4m/s，风能密度185.6W/m²，建议采用单机容量3-4.5MW风机，预期年发电小时数约2400-2600小时。',
    windSpeedMonthly: [7.8, 8.1, 7.6, 7.2, 6.8, 6.5, 6.4, 6.7, 7.2, 7.5, 7.9, 8.2],
    ghiMonthly: [],
    temperatureMonthly: [-18.5, -15.2, -8.4, 5.6, 15.8, 22.4, 24.6, 23.1, 16.8, 4.3, -6.7, -16.2],
  );

  static final FinancialModel mockFinancialModel = FinancialModel(
    id: 'fin_001',
    modelType: 'solar_pv',
    modelName: '山东光伏方案A（固定式）',
    capacityMwp: 100.0,
    capexTotal: 48500.0,
    opexAnnual: 287.5,
    electricityPrice: 0.35,
    irrEquity: 12.47,
    npv: 4523.0,
    lcoe: 0.2186,
    paybackStatic: 8.2,
    annualCashflow: [
      -48500.0,
      1245.3,
      1356.8,
      1287.5,
      1398.2,
      1456.9,
      1512.3,
      1487.6,
      1543.8,
      1598.2,
      1625.4,
      1687.9,
      1728.3,
      1756.8,
      1802.4,
      1834.6,
      1876.5,
      1912.3,
      1945.8,
      1982.4,
      2018.6,
      2045.9,
      2078.3,
      2105.6,
      2138.9,
    ],
  );

  static final DiagnosticReport mockHealthReport = DiagnosticReport(
    id: 'diag_001',
    diagnosisType: 'health',
    healthScore: 82.0,
    findings: [
      DiagnosticFinding(
        id: 'finding_001',
        severity: 'critical',
        category: '逆变器',
        description: 'PCS-12号机组输出功率下降15%，需要立即检修',
        impact: '月度发电量损失约12500kWh，经济损失约4375元',
        foundAt: DateTime.now().subtract(Duration(days: 3)),
      ),
      DiagnosticFinding(
        id: 'finding_002',
        severity: 'warning',
        category: '组件',
        description: '检测到3块太阳能电池板积灰严重，清洁效率下降20%',
        impact: '局部阵列输出功率下降8%，年损失约1850kWh',
        foundAt: DateTime.now().subtract(Duration(days: 7)),
      ),
      DiagnosticFinding(
        id: 'finding_003',
        severity: 'warning',
        category: '通信',
        description: '数据采集模块信号丢失间歇性出现',
        impact: '数据完整性受影响，无法准确监测部分设备状态',
        foundAt: DateTime.now().subtract(Duration(days: 14)),
      ),
      DiagnosticFinding(
        id: 'finding_004',
        severity: 'info',
        category: '综合PR',
        description: 'Performance Ratio为77.8%，在合理范围内',
        impact: '正常运维，建议继续观察',
        foundAt: DateTime.now().subtract(Duration(days: 1)),
      ),
    ],
    economicImpact: {
      'monthlyLoss': 4375.0,
      'annualizedLoss': 52500.0,
      'repairCost': 8500.0,
      'roi': 156.0,
    },
    recommendations: [
      DiagnosticRecommendation(
        id: 'rec_001',
        priority: 'high',
        title: '紧急：更换逆变器',
        action: '联系厂商进行PCS-12号机组的故障诊断与维修',
        expectedBenefit: '恢复发电功率，月度增收约4375元',
        estimatedCost: 8500.0,
      ),
      DiagnosticRecommendation(
        id: 'rec_002',
        priority: 'high',
        title: '清洁太阳能电池板',
        action: '安排专业团队进行全面清洁和积灰清理',
        expectedBenefit: '提升发电效率8-12%，月度增收约2100-3200元',
        estimatedCost: 1200.0,
      ),
      DiagnosticRecommendation(
        id: 'rec_003',
        priority: 'medium',
        title: '通信模块检修',
        action: '检查数据采集设备的信号强度和连接状态',
        expectedBenefit: '确保数据准确性，支持更好的运维决策',
        estimatedCost: 500.0,
      ),
    ],
  );

  static final List<Map<String, dynamic>> mockPapers = [
    {
      'id': 'paper_001',
      'title': '大型地面光伏电站性能评估与优化策略研究',
      'authors': ['王明', '李晓华', '张建国'],
      'year': 2023,
      'journal': '太阳能学报',
      'volume': '44',
      'issue': '3',
      'pages': '245-256',
      'abstract': '本文基于五年运营数据，对500MW级地面光伏电站的性能进行了全面评估，提出了基于AI的预测性维护模型...',
      'keywords': ['光伏', '性能评估', '故障诊断', '运维优化'],
      'citations': 45,
      'doi': '10.1234/tai.2023.0045',
    },
    {
      'id': 'paper_002',
      'title': '新型2.5MW风机在复杂地形中的应用研究',
      'authors': ['陈少华', '胡建军'],
      'year': 2023,
      'journal': '中国可再生能源学报',
      'volume': '13',
      'issue': '7',
      'pages': '876-892',
      'abstract': '针对复杂地形风电场的风机选型问题，通过风洞试验和实际运营数据，论证了新型2.5MW风机的优越性...',
      'keywords': ['风电', '风机选型', '复杂地形', 'CFD模拟'],
      'citations': 32,
      'doi': '10.1234/zhg.2023.0876',
    },
    {
      'id': 'paper_003',
      'title': '储能系统在新能源消纳中的关键作用分析',
      'authors': ['周琼', '刘向阳', '王红军', '葛岭'],
      'year': 2023,
      'journal': '电力系统自动化',
      'volume': '47',
      'issue': '12',
      'pages': '1-10',
      'abstract': '本论文从系统调度角度分析了储能对可再生能源并网的支撑作用，建立了经济性评估模型...',
      'keywords': ['储能', '新能源消纳', '系统调度', '经济评估'],
      'citations': 67,
      'doi': '10.1234/dlx.2023.0001',
    },
    {
      'id': 'paper_004',
      'title': '光伏+储能微网的能量管理优化控制策略',
      'authors': ['罗天娇', '欧阳明高'],
      'year': 2022,
      'journal': '中国电机工程学报',
      'volume': '42',
      'issue': '18',
      'pages': '6475-6487',
      'abstract': '针对孤岛运行微网的稳定性问题，提出了基于模型预测控制的能量管理策略...',
      'keywords': ['微网', '光伏', '储能', '能量管理', 'MPC'],
      'citations': 54,
      'doi': '10.1234/zdj.2022.6475',
    },
    {
      'id': 'paper_005',
      'title': '分布式光伏发电系统的防火与安全运维综述',
      'authors': ['刘建国', '王腊梅'],
      'year': 2023,
      'journal': '高电压技术',
      'volume': '49',
      'issue': '4',
      'pages': '1230-1245',
      'abstract': '综合分析了分布式光伏系统的火灾风险，提出了预防与应急响应的完整方案...',
      'keywords': ['分布式光伏', '防火', '安全运维', '风险评估'],
      'citations': 28,
      'doi': '10.1234/gyd.2023.1230',
    },
  ];

  static final Map<String, dynamic> mockDashboardMetrics = {
    'todayGeneration': 245600.0,
    'todayRevenue': 97024.0,
    'carbonReduction': 128.5,
    'healthScore': 82.0,
    'monthGeneration': 6845200.0,
    'monthRevenue': 2688204.0,
    'monthCarbonReduction': 3582.4,
    'trendGeneration': 8.5,
    'trendRevenue': 8.5,
    'trendCarbon': 8.5,
    'weeklyData': [
      {'day': '周一', 'generation': 198400.0},
      {'day': '周二', 'generation': 215300.0},
      {'day': '周三', 'generation': 201800.0},
      {'day': '周四', 'generation': 228600.0},
      {'day': '周五', 'generation': 245600.0},
      {'day': '周六', 'generation': 264200.0},
      {'day': '周日', 'generation': 278900.0},
    ],
  };
}
